---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"         # use node identity
    userAssignedIdentityID: <uami-client-id>   # optional, if UAMI used
    keyvaultName: <kv-name>
    objects: |
      array:
        - |
          objectName: my-secret
          objectType: secret
    tenantId: <tenant-id>
---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-cert-spc
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                   # using node identity
    userAssignedIdentityID: <uami-client-id>       # optional, required if UAMI
    keyvaultName: <kv-name>
    objects: |
      array:
        - |
          objectName: my-cert
          objectType: secret                       # certificate as a secret (base64 PFX)
          objectVersion: ""                        # optional, "" = latest
    tenantId: <tenant-id>


---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-kv
  namespace: dev
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets"
      readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: akv-secrets
